// NEWS

export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";

// ARTICLE DISPLAY

export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_ERROR = "FETCH_ARTICLE_ERROR";

// ARTICLE CLEANUP

export const CLEAR_ACTIVE_ARTICLE = "CLEAR_ACTIVE_ARTICLE";


// ARTICLE DELETE

export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_ERROR = "DELETE_ARTICLE_ERROR";
